# Project information
site_name: Future Makers STEAM Course Kit
site_description: The Future Makers is the open source course kit for STEAM education.
copyright: Copyright &copy; All rights reserved. 2017 - 2024 Beets Limited
site_url: https://futuremakers.beets3d.com/
repo_url: https://github.com/beets3d/FutureMakers
# extra_css:
#   - assets/stylesheets/extra.css

# extra_javascript:
#   - assets/javascripts/extra.js

# Configuration
theme:
  name: material
  custom_dir: docs/overrides
  language: en
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.top
    - navigation.footer
    - navigation.indexes
    - navigation.tracking
    - search.suggest
    - search.highlight
    - content.tabs
    - content.code.annotation
    - content.code.copy
    - content.tabs.link
    - toc.follow
  font:
    text: Roboto
    code: Roboto Mono
  logo: assets/beets-logo-square.avif
  favicon: images/favicon.ico
  static_templates:
    - sitemap.xml
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  extra:
    homepage: https://futuremakers.beets3d.com/
    author: true
  icon:
    admonition:
      note: fontawesome/solid/note-sticky
      abstract: fontawesome/solid/book
      info: fontawesome/solid/circle-info
      tip: fontawesome/solid/bullhorn
      success: fontawesome/solid/check
      question: fontawesome/solid/circle-question
      warning: fontawesome/solid/triangle-exclamation
      failure: fontawesome/solid/bomb
      danger: fontawesome/solid/skull
      bug: fontawesome/solid/robot
      example: fontawesome/solid/flask
      quote: fontawesome/solid/quote-left
  toc_depth: 3

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/beets3d/FutureMakers
      name: FutureMakers on Github
  consent:
    title: Cookie Consent
    description: >- 
      We use cookies to enhance quality of docs content, analyse site effectiveness and needs. 
      By consenting, you help us improve our website. Thanks!
  generator: false

markdown_extensions:
  - tables
  # Enables admonitions
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  # Enables emoji shortcodes like :+1: or :sunglasses:
  - attr_list
  - md_in_html
  - toc:
      permalink: ¶
      toc_depth: 4


plugins:
  - glightbox
  - plantuml:
        puml_url: https://www.plantuml.com/plantuml/
        num_workers: 2
  - search:
      lang:
        - en
        - zh_HK
  - tags:
      tags_file: tags.md
  - i18n:
      docs_structure: suffix
      fallback_to_default: true
      reconfigure_material: true
      reconfigure_search: true
      languages:
        - locale: en
          default: true
          name: English
          build: true
          site_name: "Future Makers: Hands-On STEAM Projects Kit"
        - locale: zh_HK 
          name: 繁體中文 (香港)
          build: true
          site_name: "未來創客: 動手做STEAM專案套裝"
          nav_translations:
            Home: 首页
            Projects: 專案
            Resources: 資源
            Reference: 參考
            Glossary: 詞彙表
            Double Side Character: 雙面字
            Lesson 1: 第一課
            Handbook: 指南
            Lesson Plan: 教案
            Exercise Cards: 練習卡
            Teaching Tips: 教學提示
            Materials: 材料
          nav_translations:
            Home: 首頁
            Projects: 專案
            Resources: 資源
            Reference: 參考
            Glossary: 詞彙表
            Double Side Character: 雙面字
            Lesson 1: 第一課
            Handbook: 指南
            Lesson Plan: 教案
            Exercise Cards: 練習卡
            Teaching Tips: 教學提示
            Materials: 材料
            Additional Concepts: 附加概念
            Assembly Guide: 組裝指南
            Gait Diagramming: 步態圖示
            Teeter-Totter Test: 翹翹板測試
            Concepts of Walking: 行走概念
            Project 00 Getting to Know Nomad Sculpt: Nomad Sculpt 指南
            Project 01 Moai: 摩艾石像 練習 1
            Project 02 Chiikawa: Chiikawa 練習 2
            Microbit Integration: Micro:bit 整合指南




nav:
  - Home: index.md
  - Setup: setup.md
  - Projects:

    - 3D AI Sculpture: 
      - Overview: projects/3d-ai-sculpture/index.md
    - Walking Robot (B3D1):
      - Overview: projects/walking-robot/index.md
      - Additional Concepts:
        - Concepts of Walking: projects/walking-robot/concept-of-walking.md
        - Assembly Guide: projects/walking-robot/assembly-guide.md
        - Gait Diagramming: projects/walking-robot/exercise-gait-diagramming.md
        - Teeter-Totter Test: projects/walking-robot/exercise-teeter-totter-test.md
    - Car Project:
        - Overview: projects/car-project/index.md
    - Singing Chiikawa:
        - Overview: projects/singing-chiikawa/index.md
        - Additional Concepts:
          - Microbit Integration: projects/singing-chiikawa/optional-microbit.md

  - Resources:
    - Assessment: resources/assessment/index.md
    - Teaching Tips: resources/teaching-tips/index.md
    - Materials: resources/materials/index.md
    - Project 00 Getting to Know Nomad Sculpt: resources/getting-to-know-nomad-sculpt/index.md
    - Project 01 Moai: resources/project-moai/index.md
    - Project 02 Chiikawa: resources/project-chiikawa/index.md

  - Reference:
    - Glossary: reference/glossary.md
    - FAQ: reference/faq.md
    - Troubleshooting: reference/troubleshooting.md

extra_css:
  - assets/stylesheets/extra.css
