# Project information
site_name: Future Makers STEAM Course Kit
site_description: The Future Makers is the open source course kit for STEAM education.
copyright: Copyright &copy; All rights reserved. 2017 - 2024 Beets Limited
site_url: https://beets3d.github.io/
# extra_css:
#   - assets/stylesheets/extra.css

# extra_javascript:
#   - assets/javascripts/extra.js

# Configuration
theme:
  name: material
  custom_dir: docs/overrides
  language: en
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.footer
    - navigation.indexes
    - navigation.tracking
    - search.suggest
    - search.highlight
    - content.tabs
    - content.code.annotation
    - content.code.copy
    - content.tabs.link
    - toc.integrate
    - toc.follow
  font:
    text: Roboto
    code: Roboto Mono
  logo: assets/beets-logo-square.avif
  favicon: images/favicon.ico
  static_templates:
    - sitemap.xml
  palette:
    primary: indigo
    accent: orange
  extra:
    homepage: https://beets3d.github.io/
  icon:
    admonition:
      note: fontawesome/solid/note-sticky
      abstract: fontawesome/solid/book
      info: fontawesome/solid/circle-info
      tip: fontawesome/solid/bullhorn
      success: fontawesome/solid/check
      question: fontawesome/solid/circle-question
      warning: fontawesome/solid/triangle-exclamation
      failure: fontawesome/solid/bomb
      danger: fontawesome/solid/skull
      bug: fontawesome/solid/robot
      example: fontawesome/solid/flask
      quote: fontawesome/solid/quote-left
  toc_depth: 3

markdown_extensions:
  - tables
  # Enables admonitions
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  # Enables emoji shortcodes like :+1: or :sunglasses:
  - attr_list
  - md_in_html
  - toc:
      permalink: ¶
      toc_depth: 3

plugins:
  - glightbox
  - search:
      lang:
        - en
        - zh_HK
  - tags:
      tags_file: tags.md
  - i18n:
      docs_structure: suffix
      fallback_to_default: true
      reconfigure_material: true
      reconfigure_search: true
      languages:
        - locale: en
          default: true
          name: English
          build: true
          site_name: "Future Makers: Hands-On STEAM Projects Kit"
        - locale: zh_HK 
          name: 繁體中文 (香港)
          build: true
          site_name: "未來創客: 動手做STEAM專案套裝"
          theme:
            palette:
              primary: grey
          nav_translations:
            Home: 首页
            Projects: 專案
            Resources: 資源
            Reference: 參考
            Glossary: 詞彙表
            Double Side Character: 雙面字
            Lesson 1: 第一課
            Overview: 概覽
            Handbook: 指南
            Lesson Plan: 教案
            Exercise Cards: 練習卡

extra:
  consent:
    title: Cookie Consent
    description: >- 
      We use cookies to enhance quality of docs content, analyse site effectiveness and needs. 
      By consenting, you help us improve our website. Thanks!
  generator: false


nav:
  - Home: index.md
  - Projects:
    - Double Side Character: 
      - Overview: projects/double-side-character/index.md
      - Lesson 1:
        - Overview: projects/double-side-character/lesson1/index.md
        - Handbook: projects/double-side-character/lesson1/handbook.md
        - Lesson Plan: projects/double-side-character/lesson1/lesson-plan.md
        - Exercise Cards: projects/double-side-character/lesson1/exercise-cards.md
  - Resources:
    - Assessment: resources/assessment/index.md
    - Teaching Tips: resources/teaching-tips/index.md
    - Materials: resources/materials/index.md
  - Reference:
    - Glossary: reference/glossary.md
    - FAQ: reference/faq.md
    - Troubleshooting: reference/troubleshooting.md
